# Generated by Django 4.1.7 on 2023-06-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_reviewproduct_remove_newsletter_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
